//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/InputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputSystem_Actions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputSystem_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                {
                    ""name"": ""Player1 Buzz Press"",
                    ""type"": ""Button"",
                    ""id"": ""6c2ab1b8-8984-453a-af3d-a3c78ae1679a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player1 Blue"",
                    ""type"": ""Button"",
                    ""id"": ""852140f2-7766-474d-8707-702459ba45f3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player1 Orange"",
                    ""type"": ""Button"",
                    ""id"": ""27c5f898-bc57-4ee1-8800-db469aca5fe3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player1 Green"",
                    ""type"": ""Button"",
                    ""id"": ""f1ba0d36-48eb-4cd5-b651-1c94a6531f70"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player1 Yellow"",
                    ""type"": ""Button"",
                    ""id"": ""2776c80d-3c14-4091-8c56-d04ced07a2b0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2 Buzz Press"",
                    ""type"": ""Button"",
                    ""id"": ""bbc8effe-08f3-4cb8-a7f5-62a655a84de9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2 Blue"",
                    ""type"": ""Button"",
                    ""id"": ""c20a6b47-9fb7-418e-a616-1bf4fafd8b59"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2 Orange"",
                    ""type"": ""Button"",
                    ""id"": ""bcb1fdeb-288b-41fc-b1ae-34397909dfc4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2 Green"",
                    ""type"": ""Button"",
                    ""id"": ""0c1f36ec-f705-4a10-9359-96574e03bb17"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2 Yellow"",
                    ""type"": ""Button"",
                    ""id"": ""89432e43-527e-4eca-b15a-d4a71f9f6eac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3 Buzz Press"",
                    ""type"": ""Button"",
                    ""id"": ""0b148354-3cff-4d4c-a50c-37c0be2bc4a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3 Blue"",
                    ""type"": ""Button"",
                    ""id"": ""035992e2-db7d-4776-8ef9-ac86903bcaa1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3 Orange"",
                    ""type"": ""Button"",
                    ""id"": ""735ae5f6-16ae-4912-8d0a-b48d9b3fe49a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3 Green"",
                    ""type"": ""Button"",
                    ""id"": ""5555b4e9-f196-4d9f-a090-763ef910d492"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player3 Yellow"",
                    ""type"": ""Button"",
                    ""id"": ""3c70ead7-53fe-4ac5-b1dd-91c676509d67"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4 Buzz Press"",
                    ""type"": ""Button"",
                    ""id"": ""a72323be-4849-49f5-9f20-9d213b7f5360"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4 Blue"",
                    ""type"": ""Button"",
                    ""id"": ""69ddd083-51e7-4e17-affb-ca52cc26c946"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4 Orange"",
                    ""type"": ""Button"",
                    ""id"": ""51ee1e28-53af-47b1-a518-2014b5f905b9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4 Green"",
                    ""type"": ""Button"",
                    ""id"": ""d2beb097-801d-4023-90b9-dedd432a367e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player4 Yellow"",
                    ""type"": ""Button"",
                    ""id"": ""ee3c2bfb-0423-4da0-8854-516d0e731f6b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControllerLeftJoyStick"",
                    ""type"": ""Value"",
                    ""id"": ""21302c0d-2ba1-4fa5-9b86-f0ad0bbee0ba"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ControllerSouth"",
                    ""type"": ""Button"",
                    ""id"": ""c0f31d17-00ec-4e09-88a8-46917ae7ac35"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c9c021b6-8b44-4377-824f-34b7d8d13ac8"",
                    ""path"": ""<HID::Namtai Buzz>/button6"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4401f8e0-7764-48a8-9973-6ec16e0c1599"",
                    ""path"": ""<HID::54C-1000>/button6"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d932777f-5c3d-40bd-af1c-afc16b201300"",
                    ""path"": ""<HID::Namtai Buzz>/trigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0763eac8-ffbc-4156-907e-be5f85e0f1a7"",
                    ""path"": ""<HID::54C-1000>/trigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d2b9c9d-990e-4ef5-9aab-fc685eab104c"",
                    ""path"": ""<HID::Namtai Buzz>/button11"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08fba6f6-7863-4b94-b9d4-cab8fd32fd2a"",
                    ""path"": ""<HID::54C-1000>/button11"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df3e82db-bc2f-40de-a1bc-622f74541c89"",
                    ""path"": ""<HID::Namtai Buzz>/button16"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3143c6a5-2156-41f1-b282-d330a1518dde"",
                    ""path"": ""<HID::54C-1000>/button16"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Buzz Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea36a5b1-3e6c-4891-bc9d-1b830cfc5c7c"",
                    ""path"": ""<HID::Namtai Buzz>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eae4a59-492e-4b57-9919-df6cc153349d"",
                    ""path"": ""<HID::54C-1000>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10fb5bbd-9668-40c5-8845-fa1ef2f70dfb"",
                    ""path"": ""<HID::Namtai Buzz>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abcb9d11-62d7-40fb-8908-1cc154e83490"",
                    ""path"": ""<HID::54C-1000>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e809b55-29bf-4afd-9ac5-f43e5aa2161e"",
                    ""path"": ""<HID::Namtai Buzz>/button13"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3363758-8202-473f-9cd0-77c62b697104"",
                    ""path"": ""<HID::54C-1000>/button13"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""542ee1f3-72ea-4b63-90e0-0039282da4e0"",
                    ""path"": ""<HID::Namtai Buzz>/button18"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f1ec8cb-1c9a-4265-bc65-58eda4871558"",
                    ""path"": ""<HID::54C-1000>/button18"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Green"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa8e0297-fd9d-49be-873e-df963d83f6a2"",
                    ""path"": ""<HID::Namtai Buzz>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccd4f871-f4c1-4db3-bd8a-f2817bf853fd"",
                    ""path"": ""<HID::54C-1000>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57451cb3-b21f-4d30-a59c-68be763ce60b"",
                    ""path"": ""<HID::Namtai Buzz>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""574a9754-7e7c-488d-83bc-42262d313e0a"",
                    ""path"": ""<HID::54C-1000>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""272e241d-b774-4e24-9c99-dad583da12a0"",
                    ""path"": ""<HID::Namtai Buzz>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18635d02-07be-472d-b4ab-fa6fd8e956af"",
                    ""path"": ""<HID::54C-1000>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dc50b2a-b1e2-4029-a2d1-303b49c8fb77"",
                    ""path"": ""<HID::Namtai Buzz>/button17"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3aa36dae-2d7a-4d34-af4b-21d278255d4c"",
                    ""path"": ""<HID::54C-1000>/button17"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Yellow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01211525-2114-43d5-b429-c2b75135303c"",
                    ""path"": ""<HID::Namtai Buzz>/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a99ef9e5-06cf-4355-951a-47a9ad6e6627"",
                    ""path"": ""<HID::54C-1000>/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa9d3550-aa1c-463e-8da7-0bf20f5d7c1e"",
                    ""path"": ""<HID::Namtai Buzz>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41f13b4a-bbb5-491e-a54f-7bcbea4a7a47"",
                    ""path"": ""<HID::54C-1000>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f37f1346-4fa7-41ab-8811-307f25253aaf"",
                    ""path"": ""<HID::Namtai Buzz>/button15"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b39c1ff-cf93-4975-bebe-5af27a9a66cf"",
                    ""path"": ""<HID::54C-1000>/button15"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0372fb0-0e34-4f0f-9235-70cc71e09c80"",
                    ""path"": ""<HID::Namtai Buzz>/button20"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97f4c551-b326-4fcb-a8f3-7f9663d27265"",
                    ""path"": ""<HID::54C-1000>/button20"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Blue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f900844-b29b-4251-90f8-4d1d7a6df09e"",
                    ""path"": ""<HID::Namtai Buzz>/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3332beb-df69-40ce-a317-2f4821d196c1"",
                    ""path"": ""<HID::54C-1000>/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player1 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b237aa3-a359-419d-96c8-328b8c27aa76"",
                    ""path"": ""<HID::Namtai Buzz>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""652aa4c1-413c-4f7d-87b3-17a99f31efa6"",
                    ""path"": ""<HID::54C-1000>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player2 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e0a19d4-d876-4145-803e-31a8684754f3"",
                    ""path"": ""<HID::Namtai Buzz>/button14"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7be985d1-880e-4796-8f64-d712f02e2580"",
                    ""path"": ""<HID::54C-1000>/button14"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player3 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""304ce41b-b37e-4b27-bc75-d1c50bc20676"",
                    ""path"": ""<HID::Namtai Buzz>/button19"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfad1aae-9302-4b36-998d-ef785161f28f"",
                    ""path"": ""<HID::54C-1000>/button19"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Buzz"",
                    ""action"": ""Player4 Orange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcd7fb7a-2d77-4025-b3ea-b47efd1ee67b"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerLeftJoyStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64ca215e-4310-4bff-828c-1683099578db"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControllerSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Buzz"",
            ""bindingGroup"": ""Buzz"",
            ""devices"": [
                {
                    ""devicePath"": ""<HID::Namtai Buzz>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Player1BuzzPress = m_Player.FindAction("Player1 Buzz Press", throwIfNotFound: true);
        m_Player_Player1Blue = m_Player.FindAction("Player1 Blue", throwIfNotFound: true);
        m_Player_Player1Orange = m_Player.FindAction("Player1 Orange", throwIfNotFound: true);
        m_Player_Player1Green = m_Player.FindAction("Player1 Green", throwIfNotFound: true);
        m_Player_Player1Yellow = m_Player.FindAction("Player1 Yellow", throwIfNotFound: true);
        m_Player_Player2BuzzPress = m_Player.FindAction("Player2 Buzz Press", throwIfNotFound: true);
        m_Player_Player2Blue = m_Player.FindAction("Player2 Blue", throwIfNotFound: true);
        m_Player_Player2Orange = m_Player.FindAction("Player2 Orange", throwIfNotFound: true);
        m_Player_Player2Green = m_Player.FindAction("Player2 Green", throwIfNotFound: true);
        m_Player_Player2Yellow = m_Player.FindAction("Player2 Yellow", throwIfNotFound: true);
        m_Player_Player3BuzzPress = m_Player.FindAction("Player3 Buzz Press", throwIfNotFound: true);
        m_Player_Player3Blue = m_Player.FindAction("Player3 Blue", throwIfNotFound: true);
        m_Player_Player3Orange = m_Player.FindAction("Player3 Orange", throwIfNotFound: true);
        m_Player_Player3Green = m_Player.FindAction("Player3 Green", throwIfNotFound: true);
        m_Player_Player3Yellow = m_Player.FindAction("Player3 Yellow", throwIfNotFound: true);
        m_Player_Player4BuzzPress = m_Player.FindAction("Player4 Buzz Press", throwIfNotFound: true);
        m_Player_Player4Blue = m_Player.FindAction("Player4 Blue", throwIfNotFound: true);
        m_Player_Player4Orange = m_Player.FindAction("Player4 Orange", throwIfNotFound: true);
        m_Player_Player4Green = m_Player.FindAction("Player4 Green", throwIfNotFound: true);
        m_Player_Player4Yellow = m_Player.FindAction("Player4 Yellow", throwIfNotFound: true);
        m_Player_ControllerLeftJoyStick = m_Player.FindAction("ControllerLeftJoyStick", throwIfNotFound: true);
        m_Player_ControllerSouth = m_Player.FindAction("ControllerSouth", throwIfNotFound: true);
    }

    ~@InputSystem_Actions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputSystem_Actions.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Player1BuzzPress;
    private readonly InputAction m_Player_Player1Blue;
    private readonly InputAction m_Player_Player1Orange;
    private readonly InputAction m_Player_Player1Green;
    private readonly InputAction m_Player_Player1Yellow;
    private readonly InputAction m_Player_Player2BuzzPress;
    private readonly InputAction m_Player_Player2Blue;
    private readonly InputAction m_Player_Player2Orange;
    private readonly InputAction m_Player_Player2Green;
    private readonly InputAction m_Player_Player2Yellow;
    private readonly InputAction m_Player_Player3BuzzPress;
    private readonly InputAction m_Player_Player3Blue;
    private readonly InputAction m_Player_Player3Orange;
    private readonly InputAction m_Player_Player3Green;
    private readonly InputAction m_Player_Player3Yellow;
    private readonly InputAction m_Player_Player4BuzzPress;
    private readonly InputAction m_Player_Player4Blue;
    private readonly InputAction m_Player_Player4Orange;
    private readonly InputAction m_Player_Player4Green;
    private readonly InputAction m_Player_Player4Yellow;
    private readonly InputAction m_Player_ControllerLeftJoyStick;
    private readonly InputAction m_Player_ControllerSouth;
    public struct PlayerActions
    {
        private @InputSystem_Actions m_Wrapper;
        public PlayerActions(@InputSystem_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Player1BuzzPress => m_Wrapper.m_Player_Player1BuzzPress;
        public InputAction @Player1Blue => m_Wrapper.m_Player_Player1Blue;
        public InputAction @Player1Orange => m_Wrapper.m_Player_Player1Orange;
        public InputAction @Player1Green => m_Wrapper.m_Player_Player1Green;
        public InputAction @Player1Yellow => m_Wrapper.m_Player_Player1Yellow;
        public InputAction @Player2BuzzPress => m_Wrapper.m_Player_Player2BuzzPress;
        public InputAction @Player2Blue => m_Wrapper.m_Player_Player2Blue;
        public InputAction @Player2Orange => m_Wrapper.m_Player_Player2Orange;
        public InputAction @Player2Green => m_Wrapper.m_Player_Player2Green;
        public InputAction @Player2Yellow => m_Wrapper.m_Player_Player2Yellow;
        public InputAction @Player3BuzzPress => m_Wrapper.m_Player_Player3BuzzPress;
        public InputAction @Player3Blue => m_Wrapper.m_Player_Player3Blue;
        public InputAction @Player3Orange => m_Wrapper.m_Player_Player3Orange;
        public InputAction @Player3Green => m_Wrapper.m_Player_Player3Green;
        public InputAction @Player3Yellow => m_Wrapper.m_Player_Player3Yellow;
        public InputAction @Player4BuzzPress => m_Wrapper.m_Player_Player4BuzzPress;
        public InputAction @Player4Blue => m_Wrapper.m_Player_Player4Blue;
        public InputAction @Player4Orange => m_Wrapper.m_Player_Player4Orange;
        public InputAction @Player4Green => m_Wrapper.m_Player_Player4Green;
        public InputAction @Player4Yellow => m_Wrapper.m_Player_Player4Yellow;
        public InputAction @ControllerLeftJoyStick => m_Wrapper.m_Player_ControllerLeftJoyStick;
        public InputAction @ControllerSouth => m_Wrapper.m_Player_ControllerSouth;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Player1BuzzPress.started += instance.OnPlayer1BuzzPress;
            @Player1BuzzPress.performed += instance.OnPlayer1BuzzPress;
            @Player1BuzzPress.canceled += instance.OnPlayer1BuzzPress;
            @Player1Blue.started += instance.OnPlayer1Blue;
            @Player1Blue.performed += instance.OnPlayer1Blue;
            @Player1Blue.canceled += instance.OnPlayer1Blue;
            @Player1Orange.started += instance.OnPlayer1Orange;
            @Player1Orange.performed += instance.OnPlayer1Orange;
            @Player1Orange.canceled += instance.OnPlayer1Orange;
            @Player1Green.started += instance.OnPlayer1Green;
            @Player1Green.performed += instance.OnPlayer1Green;
            @Player1Green.canceled += instance.OnPlayer1Green;
            @Player1Yellow.started += instance.OnPlayer1Yellow;
            @Player1Yellow.performed += instance.OnPlayer1Yellow;
            @Player1Yellow.canceled += instance.OnPlayer1Yellow;
            @Player2BuzzPress.started += instance.OnPlayer2BuzzPress;
            @Player2BuzzPress.performed += instance.OnPlayer2BuzzPress;
            @Player2BuzzPress.canceled += instance.OnPlayer2BuzzPress;
            @Player2Blue.started += instance.OnPlayer2Blue;
            @Player2Blue.performed += instance.OnPlayer2Blue;
            @Player2Blue.canceled += instance.OnPlayer2Blue;
            @Player2Orange.started += instance.OnPlayer2Orange;
            @Player2Orange.performed += instance.OnPlayer2Orange;
            @Player2Orange.canceled += instance.OnPlayer2Orange;
            @Player2Green.started += instance.OnPlayer2Green;
            @Player2Green.performed += instance.OnPlayer2Green;
            @Player2Green.canceled += instance.OnPlayer2Green;
            @Player2Yellow.started += instance.OnPlayer2Yellow;
            @Player2Yellow.performed += instance.OnPlayer2Yellow;
            @Player2Yellow.canceled += instance.OnPlayer2Yellow;
            @Player3BuzzPress.started += instance.OnPlayer3BuzzPress;
            @Player3BuzzPress.performed += instance.OnPlayer3BuzzPress;
            @Player3BuzzPress.canceled += instance.OnPlayer3BuzzPress;
            @Player3Blue.started += instance.OnPlayer3Blue;
            @Player3Blue.performed += instance.OnPlayer3Blue;
            @Player3Blue.canceled += instance.OnPlayer3Blue;
            @Player3Orange.started += instance.OnPlayer3Orange;
            @Player3Orange.performed += instance.OnPlayer3Orange;
            @Player3Orange.canceled += instance.OnPlayer3Orange;
            @Player3Green.started += instance.OnPlayer3Green;
            @Player3Green.performed += instance.OnPlayer3Green;
            @Player3Green.canceled += instance.OnPlayer3Green;
            @Player3Yellow.started += instance.OnPlayer3Yellow;
            @Player3Yellow.performed += instance.OnPlayer3Yellow;
            @Player3Yellow.canceled += instance.OnPlayer3Yellow;
            @Player4BuzzPress.started += instance.OnPlayer4BuzzPress;
            @Player4BuzzPress.performed += instance.OnPlayer4BuzzPress;
            @Player4BuzzPress.canceled += instance.OnPlayer4BuzzPress;
            @Player4Blue.started += instance.OnPlayer4Blue;
            @Player4Blue.performed += instance.OnPlayer4Blue;
            @Player4Blue.canceled += instance.OnPlayer4Blue;
            @Player4Orange.started += instance.OnPlayer4Orange;
            @Player4Orange.performed += instance.OnPlayer4Orange;
            @Player4Orange.canceled += instance.OnPlayer4Orange;
            @Player4Green.started += instance.OnPlayer4Green;
            @Player4Green.performed += instance.OnPlayer4Green;
            @Player4Green.canceled += instance.OnPlayer4Green;
            @Player4Yellow.started += instance.OnPlayer4Yellow;
            @Player4Yellow.performed += instance.OnPlayer4Yellow;
            @Player4Yellow.canceled += instance.OnPlayer4Yellow;
            @ControllerLeftJoyStick.started += instance.OnControllerLeftJoyStick;
            @ControllerLeftJoyStick.performed += instance.OnControllerLeftJoyStick;
            @ControllerLeftJoyStick.canceled += instance.OnControllerLeftJoyStick;
            @ControllerSouth.started += instance.OnControllerSouth;
            @ControllerSouth.performed += instance.OnControllerSouth;
            @ControllerSouth.canceled += instance.OnControllerSouth;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Player1BuzzPress.started -= instance.OnPlayer1BuzzPress;
            @Player1BuzzPress.performed -= instance.OnPlayer1BuzzPress;
            @Player1BuzzPress.canceled -= instance.OnPlayer1BuzzPress;
            @Player1Blue.started -= instance.OnPlayer1Blue;
            @Player1Blue.performed -= instance.OnPlayer1Blue;
            @Player1Blue.canceled -= instance.OnPlayer1Blue;
            @Player1Orange.started -= instance.OnPlayer1Orange;
            @Player1Orange.performed -= instance.OnPlayer1Orange;
            @Player1Orange.canceled -= instance.OnPlayer1Orange;
            @Player1Green.started -= instance.OnPlayer1Green;
            @Player1Green.performed -= instance.OnPlayer1Green;
            @Player1Green.canceled -= instance.OnPlayer1Green;
            @Player1Yellow.started -= instance.OnPlayer1Yellow;
            @Player1Yellow.performed -= instance.OnPlayer1Yellow;
            @Player1Yellow.canceled -= instance.OnPlayer1Yellow;
            @Player2BuzzPress.started -= instance.OnPlayer2BuzzPress;
            @Player2BuzzPress.performed -= instance.OnPlayer2BuzzPress;
            @Player2BuzzPress.canceled -= instance.OnPlayer2BuzzPress;
            @Player2Blue.started -= instance.OnPlayer2Blue;
            @Player2Blue.performed -= instance.OnPlayer2Blue;
            @Player2Blue.canceled -= instance.OnPlayer2Blue;
            @Player2Orange.started -= instance.OnPlayer2Orange;
            @Player2Orange.performed -= instance.OnPlayer2Orange;
            @Player2Orange.canceled -= instance.OnPlayer2Orange;
            @Player2Green.started -= instance.OnPlayer2Green;
            @Player2Green.performed -= instance.OnPlayer2Green;
            @Player2Green.canceled -= instance.OnPlayer2Green;
            @Player2Yellow.started -= instance.OnPlayer2Yellow;
            @Player2Yellow.performed -= instance.OnPlayer2Yellow;
            @Player2Yellow.canceled -= instance.OnPlayer2Yellow;
            @Player3BuzzPress.started -= instance.OnPlayer3BuzzPress;
            @Player3BuzzPress.performed -= instance.OnPlayer3BuzzPress;
            @Player3BuzzPress.canceled -= instance.OnPlayer3BuzzPress;
            @Player3Blue.started -= instance.OnPlayer3Blue;
            @Player3Blue.performed -= instance.OnPlayer3Blue;
            @Player3Blue.canceled -= instance.OnPlayer3Blue;
            @Player3Orange.started -= instance.OnPlayer3Orange;
            @Player3Orange.performed -= instance.OnPlayer3Orange;
            @Player3Orange.canceled -= instance.OnPlayer3Orange;
            @Player3Green.started -= instance.OnPlayer3Green;
            @Player3Green.performed -= instance.OnPlayer3Green;
            @Player3Green.canceled -= instance.OnPlayer3Green;
            @Player3Yellow.started -= instance.OnPlayer3Yellow;
            @Player3Yellow.performed -= instance.OnPlayer3Yellow;
            @Player3Yellow.canceled -= instance.OnPlayer3Yellow;
            @Player4BuzzPress.started -= instance.OnPlayer4BuzzPress;
            @Player4BuzzPress.performed -= instance.OnPlayer4BuzzPress;
            @Player4BuzzPress.canceled -= instance.OnPlayer4BuzzPress;
            @Player4Blue.started -= instance.OnPlayer4Blue;
            @Player4Blue.performed -= instance.OnPlayer4Blue;
            @Player4Blue.canceled -= instance.OnPlayer4Blue;
            @Player4Orange.started -= instance.OnPlayer4Orange;
            @Player4Orange.performed -= instance.OnPlayer4Orange;
            @Player4Orange.canceled -= instance.OnPlayer4Orange;
            @Player4Green.started -= instance.OnPlayer4Green;
            @Player4Green.performed -= instance.OnPlayer4Green;
            @Player4Green.canceled -= instance.OnPlayer4Green;
            @Player4Yellow.started -= instance.OnPlayer4Yellow;
            @Player4Yellow.performed -= instance.OnPlayer4Yellow;
            @Player4Yellow.canceled -= instance.OnPlayer4Yellow;
            @ControllerLeftJoyStick.started -= instance.OnControllerLeftJoyStick;
            @ControllerLeftJoyStick.performed -= instance.OnControllerLeftJoyStick;
            @ControllerLeftJoyStick.canceled -= instance.OnControllerLeftJoyStick;
            @ControllerSouth.started -= instance.OnControllerSouth;
            @ControllerSouth.performed -= instance.OnControllerSouth;
            @ControllerSouth.canceled -= instance.OnControllerSouth;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    private int m_BuzzSchemeIndex = -1;
    public InputControlScheme BuzzScheme
    {
        get
        {
            if (m_BuzzSchemeIndex == -1) m_BuzzSchemeIndex = asset.FindControlSchemeIndex("Buzz");
            return asset.controlSchemes[m_BuzzSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnPlayer1BuzzPress(InputAction.CallbackContext context);
        void OnPlayer1Blue(InputAction.CallbackContext context);
        void OnPlayer1Orange(InputAction.CallbackContext context);
        void OnPlayer1Green(InputAction.CallbackContext context);
        void OnPlayer1Yellow(InputAction.CallbackContext context);
        void OnPlayer2BuzzPress(InputAction.CallbackContext context);
        void OnPlayer2Blue(InputAction.CallbackContext context);
        void OnPlayer2Orange(InputAction.CallbackContext context);
        void OnPlayer2Green(InputAction.CallbackContext context);
        void OnPlayer2Yellow(InputAction.CallbackContext context);
        void OnPlayer3BuzzPress(InputAction.CallbackContext context);
        void OnPlayer3Blue(InputAction.CallbackContext context);
        void OnPlayer3Orange(InputAction.CallbackContext context);
        void OnPlayer3Green(InputAction.CallbackContext context);
        void OnPlayer3Yellow(InputAction.CallbackContext context);
        void OnPlayer4BuzzPress(InputAction.CallbackContext context);
        void OnPlayer4Blue(InputAction.CallbackContext context);
        void OnPlayer4Orange(InputAction.CallbackContext context);
        void OnPlayer4Green(InputAction.CallbackContext context);
        void OnPlayer4Yellow(InputAction.CallbackContext context);
        void OnControllerLeftJoyStick(InputAction.CallbackContext context);
        void OnControllerSouth(InputAction.CallbackContext context);
    }
}
